[package]
name = "zatel"
version = "0.1.0"
authors = ["Gris Ge <cnfourt@gmail.com>"]
edition = "2018"

build = "build.rs"
[build-dependencies]
varlink_generator = "9"


[dependencies]
varlink = "10"
getopts = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
