[package]
name = "npd"
version = "0.3.1"
authors = ["Gris Ge <cnfourt@gmail.com>"]
edition = "2018"

[[bin]]
name = "npd"
path = "npd.rs"

[dependencies]
varlink = "10"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
nispor = { path = "../lib" }
libc = "0.2.71"
